// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkHpW_5X6YzClbL7f5TgFrPqdlElD59lI',
    appId: '1:384641051293:web:b48dbba11778636df9c274',
    messagingSenderId: '384641051293',
    projectId: 'erp-data-1c152',
    authDomain: 'erp-data-1c152.firebaseapp.com',
    storageBucket: 'erp-data-1c152.firebasestorage.app',
    measurementId: 'G-BHCED93MVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPj466ewtdABJYJ-2NmVr2rWdViIQadjc',
    appId: '1:384641051293:android:196fcfa885aa0109f9c274',
    messagingSenderId: '384641051293',
    projectId: 'erp-data-1c152',
    storageBucket: 'erp-data-1c152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0QU-H6Jkp8YYarV23F9D85Fd7_5MIz6s',
    appId: '1:384641051293:ios:8f7e3418b2f2a1a4f9c274',
    messagingSenderId: '384641051293',
    projectId: 'erp-data-1c152',
    storageBucket: 'erp-data-1c152.firebasestorage.app',
    iosBundleId: 'com.example.erpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0QU-H6Jkp8YYarV23F9D85Fd7_5MIz6s',
    appId: '1:384641051293:ios:8f7e3418b2f2a1a4f9c274',
    messagingSenderId: '384641051293',
    projectId: 'erp-data-1c152',
    storageBucket: 'erp-data-1c152.firebasestorage.app',
    iosBundleId: 'com.example.erpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkHpW_5X6YzClbL7f5TgFrPqdlElD59lI',
    appId: '1:384641051293:web:0f732557ef0d51b3f9c274',
    messagingSenderId: '384641051293',
    projectId: 'erp-data-1c152',
    authDomain: 'erp-data-1c152.firebaseapp.com',
    storageBucket: 'erp-data-1c152.firebasestorage.app',
    measurementId: 'G-WMLQH7G5F3',
  );

}